apiVersion: apps/v1
kind: Deployment
metadata:
  name: montrealdb
  labels:
    app: montrealdb
spec:
  selector:
    matchLabels:
      app: montrealdb
  replicas: 1
  template:
    metadata:
      labels:
        app: montrealdb
    spec:
      containers:
        - name: montrealdb
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: montreal-db-data
          ports:
            - containerPort: 27017
              name: montrealdb-port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: app-secret
            -  name: MONGO_INITDB_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   key: db-pass
                   name: app-secret
      nodeSelector:
        zone: us-east-2a  # to indicate which zone we want our pods to run, should be same with the zone our volume is.
      volumes:
        - name: montreal-db-data
          awsElasticBlockStore:
            volumeID: vol-00c7163c62bc33ec2
            fsType: ext4